# Mendefinisikan Versi Docker Compose
version: '3.8'

# Mendefinisikan Voulmes
volumes: 
  # Untuk Menyimpan Seluruh Data Dalam Database
  localdb:

# Mendefinisikan Networks
networks:
  # Untuk Mengkoneksikan Antar Services
  localapp:

# Mendefinisikan Services Yang Akan Dipakai
services:
  # Nama Service Untuk Web Server (nginx)
  nginx:
    # Gunakan Image Nginx Tag Alpine
    image: nginx:alpine
    # Kaitkan Folder Lokal Ke Container
    volumes: 
      # Folder Web
      - "./htdocs:/var/www"
      # Folder Konfigurasi Nginx
      - "./.build/nginx/conf.d:/etc/nginx/conf.d"
    # Ekspose Port
    ports: 
    # 80 (http://localhost)
      - "80:80"
    # Jalankan Nginx Jika Service php Dan db Sudah Berjalan
    depends_on: 
      - php
      - db
    # Koneksikan Ke Network localapp
    networks: 
      - localapp

  # Nama Service Untuk PHP
  php:
    # Build Image Dengan Dockerfile Di Folder ./.build/php
    build: ./.build/php
    # Kaitkan Folder Lokal Ke Container
    volumes:
      # Jalankan PHP Di Semua Folder Web
      - "./htdocs:/var/www"
    # Koneksikan Ke Network localapp
    networks: 
      - localapp

  # Nama Service Untuk Database  
  db:
    # Gunakan Image mysql Tag latest
    image: mysql:latest
    # Environment Yang Dibutuhkan mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: homestead
    # Expose Port Agar Dapat Diakses Melalui Aplikasi MYSQL Client (phpmyadmin)
    ports: 
      - "3306:3306"
    # Simpan Semua Data Dalam Volumes localdb
    volumes: 
     - "localdb:/var/lib/mysql"
    # Koneksikan Ke Network localapp
    networks: 
      - localapp
  
  # Nama Service Untuk PHPMYADMIN
  phpmyadmin:
    # Gunakan Image phpmyadmin
    image: phpmyadmin/phpmyadmin
    # Expose Port
    ports: 
      # Gunakan Port 8081 Untuk Mengakses phpmyadmin
      - "8081:80"
    # Koneksikan Ke Network localapp
    networks: 
      - localapp